afe\afe.obj: ../afe/afe.c
afe\afe.obj: ..\afe\afe.h
afe\afe.obj: C:/ti/ccsv6/ccs_base/msp430/include/msp430.h
afe\afe.obj: C:\ti\ccsv6\ccs_base\msp430\include\msp430fr5972.h
afe\afe.obj: C:\ti\ccsv6\ccs_base\msp430\include\in430.h
afe\afe.obj: C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include/intrinsics.h
afe\afe.obj: C:\ti\ccsv6\tools\compiler\ti-cgt-msp430_4.4.3\include\intrinsics_legacy_undefs.h
afe\afe.obj: C:/ti/ccsv6/tools/compiler/ti-cgt-msp430_4.4.3/include/stdint.h
afe\afe.obj: ..\afe\afe_src/afe_serial.h
afe\afe.obj: ..\afe\afe_src\ADS1291_constants.h
afe\afe.obj: ..\afe\../utils.h
